name = "SparseGaussianProcess"
uuid = "59354e0e-2cd1-45c1-8980-bf1317082734"
authors = ["Mridul Jain"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
